namespace DiscoSdk.Commands.Localization;

/// <summary>
/// Builder for translating the choices generated by <see cref="EnumChoicesAttribute{T}"/>.
/// Returned by <see cref="OptionTranslationBuilder.ThenEnumChoice{TEnum}(Action{EnumChoiceTranslationBuilder{TEnum}})"/>.
/// Each <see cref="For(TEnum, string)"/> call adds one choice translation under the focused option,
/// using <c>value.ToString()</c> as the choice key — the same key <see cref="EnumChoicesAttribute{T}"/>
/// emits when generating choices from the enum.
/// </summary>
public sealed class EnumChoiceTranslationBuilder<TEnum> where TEnum : struct, Enum
{
    private const int MaxChoiceNameLen = 100;

    private readonly OptionScratch _parent;

    internal EnumChoiceTranslationBuilder(OptionScratch parent)
    {
        _parent = parent;
    }

    /// <summary>
    /// Sets the localized display name for a specific enum value's choice.
    /// </summary>
    public EnumChoiceTranslationBuilder<TEnum> For(TEnum value, string localizedName)
    {
        if (string.IsNullOrWhiteSpace(localizedName))
            throw new ArgumentException("Localized name cannot be null or empty.", nameof(localizedName));
        if (localizedName.Length > MaxChoiceNameLen)
            throw new ArgumentException($"Localized name cannot exceed {MaxChoiceNameLen} characters.", nameof(localizedName));

        _parent.Choices.Add(new ChoiceScratch(value.ToString()) { Name = localizedName });
        return this;
    }
}
