using System.Net.Http.Headers;
using System.Text.Json;

namespace DiscoSdk.Rest;

/// <summary>
/// Interface for making HTTP requests to the Discord REST API.
/// </summary>
public interface IDiscordRestClient : IDisposable
{
    JsonSerializerOptions JsonOptions { get; }

    /// <summary>
    /// Sends a request to the Discord API that expects no content in the response.
    /// </summary>
    /// <param name="path">The API endpoint path.</param>
    /// <param name="method">The HTTP method to use.</param>
    /// <param name="ct">Cancellation token to cancel the operation.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    Task SendAsync(DiscordRoute path, HttpMethod method, CancellationToken ct);

    /// <summary>
    /// Sends a JSON request to the Discord API and deserializes the response.
    /// </summary>
    /// <typeparam name="T">The type to deserialize the response to.</typeparam>
    /// <param name="path">The API endpoint path.</param>
    /// <param name="method">The HTTP method to use.</param>
    /// <param name="body">The request body object to serialize, or null.</param>
    /// <param name="ct">Cancellation token to cancel the operation.</param>
    /// <returns>A task that represents the asynchronous operation. The result contains the deserialized response.</returns>
    Task SendAsync(DiscordRoute path, HttpMethod method, object? body, CancellationToken ct);

    /// <summary>
    /// Sends a JSON request to the Discord API and deserializes the response.
    /// </summary>
    /// <typeparam name="T">The type to deserialize the response to.</typeparam>
    /// <param name="path">The API endpoint path.</param>
    /// <param name="method">The HTTP method to use.</param>
    /// <param name="body">The request body object to serialize, or null.</param>
    /// <param name="ct">Cancellation token to cancel the operation.</param>
    /// <returns>A task that represents the asynchronous operation. The result contains the deserialized response.</returns>
    Task<T> SendAsync<T>(DiscordRoute path, HttpMethod method, object? body, CancellationToken ct);

    /// <summary>
    /// Sends a JSON request to the Discord API and deserializes the response.
    /// </summary>
    /// <typeparam name="T">The type to deserialize the response to.</typeparam>
    /// <param name="path">The API endpoint path.</param>
    /// <param name="method">The HTTP method to use.</param>
    /// <param name="ct">Cancellation token to cancel the operation.</param>
    /// <returns>A task that represents the asynchronous operation. The result contains the deserialized response.</returns>
    Task<T> SendAsync<T>(DiscordRoute path, HttpMethod method, CancellationToken ct);

    /// <summary>
    /// Sends a request to the Discord API with an optional per-request <c>Authorization</c> header.
    /// When <paramref name="authOverride"/> is non-null it replaces the bot-token default for this
    /// request only; the client's <c>DefaultRequestHeaders</c> are never mutated. Primarily intended
    /// for OAuth2 endpoints that require HTTP Basic (<c>client_id:client_secret</c>) or bearer auth.
    /// </summary>
    Task SendAsync(DiscordRoute path, HttpMethod method, object? body, AuthenticationHeaderValue? authOverride, CancellationToken ct);

    /// <summary>
    /// Sends a request to the Discord API with an optional per-request <c>Authorization</c> header
    /// and deserializes the response. Same per-request override semantics as the non-generic overload.
    /// </summary>
    Task<T> SendAsync<T>(DiscordRoute path, HttpMethod method, object? body, AuthenticationHeaderValue? authOverride, CancellationToken ct);

    /// <summary>
    /// Sends a mutating request that records an audit-log reason. The client URL-encodes
    /// <paramref name="auditLogReason"/> and attaches it as the <c>X-Audit-Log-Reason</c> request
    /// header — Discord stores it verbatim against the audit-log entry generated by the action.
    /// Validation (length / null / empty) belongs to the caller; the client only enforces
    /// Discord's silent-truncation guard at 512 characters. Callers that have <em>no</em> reason
    /// to log should use the plain <see cref="SendAsync(DiscordRoute, HttpMethod, object?, CancellationToken)"/>
    /// — keeping the no-reason path on a distinct method preserves a clean mock surface and lets
    /// REST clients branch by reason presence without leaking <c>string?</c> into hot signatures.
    /// </summary>
    Task SendWithReasonAsync(DiscordRoute path, HttpMethod method, object? body, string auditLogReason, CancellationToken ct);

    /// <summary>
    /// Audit-log-reason counterpart of <see cref="SendAsync{T}(DiscordRoute, HttpMethod, object?, CancellationToken)"/>
    /// for endpoints that return a deserialised payload.
    /// </summary>
    Task<T> SendWithReasonAsync<T>(DiscordRoute path, HttpMethod method, object? body, string auditLogReason, CancellationToken ct);
}
